# Generated by Django 4.2 on 2026-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_passwordresettoken_user_booking_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_attendees',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
